name: Update Activity Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: rishPhoneix
          options: >-
            theme=react-dark&
            bg_color=0D1117&
            color=9D7CFF&
            line=6A0DAD&
            point=FFFFFF&
            area_color=6A0DAD&
            area=true&
            hide_border=true
          output_path: activity-graph.svg
          token: ${{ secrets.TROPHY_TOKEN }}

      - name: Commit activity graph
        uses: EndBug/add-and-commit@v9
        with:
          add: activity-graph.svg
          message: "Update GitHub activity graph"
