name: Generate GitHub Trophies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  actions: read
  pull-requests: read

jobs:
  trophies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophies
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: rishPhoneix
          file: trophy.svg
          token: ${{ secrets.TROPHY_TOKEN }}

      - name: Commit trophy SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: "trophy.svg"
          message: "Update GitHub trophies"
